import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("jars", "routes/jars.tsx"),
  route("jars/new", "routes/jars.new.tsx"),
  route("jars/:id", "routes/jars.$id.tsx"),
  route("jars/:id/edit", "routes/jars.$id.edit.tsx"),
  route("j/:slug", "routes/j.$slug.tsx"),
  route("auth/:provider", "routes/auth.$provider.tsx"),
  route("auth/:provider/callback", "routes/auth.$provider.callback.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/slug", "routes/api.slug.ts"),
  route("api/v1/links", "routes/api.v1.links.ts"),
  route("api/v1/links/token", "routes/api.v1.links.token.ts"),
  route("api/v1/links/:code", "routes/api.v1.links.$code.ts"),
  route("api/v1/links/:code/approve", "routes/api.v1.links.$code.approve.ts"),
  route("api/v1/me", "routes/api.v1.me.ts"),
  route("api/v1/devices", "routes/api.v1.devices.ts"),
  route("api/v1/devices/:id", "routes/api.v1.devices.$id.ts"),
  route("api/v1/jars", "routes/api.v1.jars.ts"),
  route("api/v1/jars/:id", "routes/api.v1.jars.$id.ts"),
  route("api/v1/slugs/:slug", "routes/api.v1.slugs.$slug.ts"),
  route("api/v1/jars/:id/fines", "routes/api.v1.jars.$id.fines.ts"),
  route("api/v1/jars/:id/fines/:fineId", "routes/api.v1.jars.$id.fines.$fineId.ts"),
  route("api/v1/jars/:id/settlements", "routes/api.v1.jars.$id.settlements.ts"),
  route("account", "routes/account.tsx"),
  route("link", "routes/link.tsx"),
  route("link/phone", "routes/link.phone.tsx"),
  route("devices", "routes/devices.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("delete-account", "routes/delete-account.tsx"),
  route(".well-known/assetlinks.json", "routes/assetlinks.ts"),
] satisfies RouteConfig;
